version: '3.9'

services:
  api:
    container_name: rickandmortyapi
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always