version: '3.9'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always

  api:
    container_name: rickandmortyapi
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - redis