name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Start all the environment
        run: docker-compose up -d

      - name: Run tests
        run: docker exec rickandmortyapi npm run test